import * as React from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { toast } from "@/hooks/use-toast";
import { Download, Copy, Mail, FileText, Check, Share2, Loader2 } from "lucide-react";
import { formatDuration } from "@/lib/conversations";
import type { MeetingItem } from "@/hooks/useMeetingItems";
import type { MeetingItemType } from "@/lib/phraseDetection";

interface ExportPanelProps {
  title: string;
  date: Date;
  durationMs: number;
  items: MeetingItem[];
  grouped: Record<MeetingItemType, MeetingItem[]>;
  summary?: {
    key_points?: string[];
    decisions?: string[];
    action_items?: string[];
    open_questions?: string[];
  } | null;
  participants?: Array<{ name: string; email?: string | null }>;
}

function generateMarkdown(props: ExportPanelProps): string {
  const { title, date, durationMs, grouped, summary, participants } = props;
  const lines: string[] = [];
  
  lines.push(`# Meeting Minutes: ${title}`);
  lines.push("");
  lines.push(`**Date:** ${date.toLocaleDateString()} at ${date.toLocaleTimeString()}`);
  lines.push(`**Duration:** ${formatDuration(durationMs)}`);
  
  if (participants && participants.length > 0) {
    lines.push(`**Participants:** ${participants.map(p => p.name).join(", ")}`);
  }
  lines.push("");

  if (summary?.key_points?.length) {
    lines.push("## Key Points");
    summary.key_points.forEach((kp) => lines.push(`- ${kp}`));
    lines.push("");
  }

  const sections: Array<{ type: MeetingItemType; emoji: string; title: string }> = [
    { type: "action_item", emoji: "✅", title: "Action Items" },
    { type: "decision", emoji: "⚖️", title: "Decisions Made" },
    { type: "question", emoji: "❓", title: "Open Questions" },
    { type: "deferred", emoji: "⏰", title: "Deferred Items" },
  ];

  for (const section of sections) {
    const sectionItems = grouped[section.type];
    if (sectionItems.length === 0) continue;

    lines.push(`## ${section.emoji} ${section.title}`);
    lines.push("");
    
    sectionItems.forEach((item, i) => {
      const owner = item.owner ? ` *(Owner: ${item.owner})*` : "";
      const timestamp = `[${formatDuration(item.timestampMs)}]`;
      lines.push(`${i + 1}. ${item.content}${owner} ${timestamp}`);
    });
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by MeetingIQ on ${new Date().toLocaleString()}*`);

  return lines.join("\n");
}

function generatePlainText(props: ExportPanelProps): string {
  const { title, date, durationMs, grouped, summary, participants } = props;
  const lines: string[] = [];
  
  lines.push(`MEETING MINUTES: ${title.toUpperCase()}`);
  lines.push("=".repeat(50));
  lines.push("");
  lines.push(`Date: ${date.toLocaleDateString()} at ${date.toLocaleTimeString()}`);
  lines.push(`Duration: ${formatDuration(durationMs)}`);
  
  if (participants && participants.length > 0) {
    lines.push(`Participants: ${participants.map(p => p.name).join(", ")}`);
  }
  lines.push("");

  if (summary?.key_points?.length) {
    lines.push("KEY POINTS:");
    summary.key_points.forEach((kp) => lines.push(`  • ${kp}`));
    lines.push("");
  }

  const sections: Array<{ type: MeetingItemType; title: string }> = [
    { type: "action_item", title: "ACTION ITEMS" },
    { type: "decision", title: "DECISIONS" },
    { type: "question", title: "OPEN QUESTIONS" },
    { type: "deferred", title: "DEFERRED" },
  ];

  for (const section of sections) {
    const sectionItems = grouped[section.type];
    if (sectionItems.length === 0) continue;

    lines.push(`${section.title}:`);
    sectionItems.forEach((item, i) => {
      const owner = item.owner ? ` (→ ${item.owner})` : "";
      lines.push(`  ${i + 1}. ${item.content}${owner}`);
    });
    lines.push("");
  }

  return lines.join("\n");
}

function generateEmailBody(props: ExportPanelProps): string {
  const { title, date, durationMs, grouped, summary } = props;
  const lines: string[] = [];
  
  lines.push(`Hi,`);
  lines.push("");
  lines.push(`Here are the notes from our meeting "${title}" on ${date.toLocaleDateString()}.`);
  lines.push("");
  
  if (summary?.key_points?.length) {
    lines.push("📋 KEY POINTS:");
    summary.key_points.forEach((kp) => lines.push(`• ${kp}`));
    lines.push("");
  }

  if (grouped.action_item.length > 0) {
    lines.push("✅ ACTION ITEMS:");
    grouped.action_item.forEach((item, i) => {
      const owner = item.owner ? ` → ${item.owner}` : "";
      lines.push(`${i + 1}. ${item.content}${owner}`);
    });
    lines.push("");
  }

  if (grouped.decision.length > 0) {
    lines.push("⚖️ DECISIONS:");
    grouped.decision.forEach((item, i) => {
      lines.push(`${i + 1}. ${item.content}`);
    });
    lines.push("");
  }

  if (grouped.question.length > 0) {
    lines.push("❓ OPEN QUESTIONS:");
    grouped.question.forEach((item, i) => {
      lines.push(`${i + 1}. ${item.content}`);
    });
    lines.push("");
  }

  lines.push("---");
  lines.push("Sent via MeetingIQ");

  return lines.join("\n");
}

export function ExportPanel(props: ExportPanelProps) {
  const { title, items, participants } = props;
  const [copied, setCopied] = React.useState(false);
  const [isGeneratingPdf, setIsGeneratingPdf] = React.useState(false);

  const markdown = React.useMemo(() => generateMarkdown(props), [props]);
  const plainText = React.useMemo(() => generatePlainText(props), [props]);
  const emailBody = React.useMemo(() => generateEmailBody(props), [props]);

  const handleCopyMarkdown = async () => {
    await navigator.clipboard.writeText(markdown);
    setCopied(true);
    toast({ title: "Copied to clipboard", description: "Markdown notes copied successfully." });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleCopyPlainText = async () => {
    await navigator.clipboard.writeText(plainText);
    setCopied(true);
    toast({ title: "Copied to clipboard", description: "Plain text notes copied successfully." });
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownloadMarkdown = () => {
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/[^a-z0-9]/gi, "_")}_minutes.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    toast({ title: "Downloaded", description: "Markdown file downloaded successfully." });
  };

  const handleDownloadPdf = async () => {
    setIsGeneratingPdf(true);
    
    // Create a simple HTML representation for PDF
    const htmlContent = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>${title} - Meeting Minutes</title>
        <style>
          body { font-family: Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; }
          h1 { color: #1a1a1a; border-bottom: 2px solid #3b82f6; padding-bottom: 10px; }
          h2 { color: #374151; margin-top: 30px; }
          .meta { color: #6b7280; margin-bottom: 20px; }
          ul, ol { margin: 10px 0; padding-left: 20px; }
          li { margin: 5px 0; }
          .footer { margin-top: 40px; padding-top: 20px; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 12px; }
        </style>
      </head>
      <body>
        ${markdown
          .replace(/^# (.+)$/gm, '<h1>$1</h1>')
          .replace(/^## (.+)$/gm, '<h2>$1</h2>')
          .replace(/^### (.+)$/gm, '<h3>$1</h3>')
          .replace(/^\*\*(.+?)\*\* (.+)$/gm, '<p><strong>$1</strong> $2</p>')
          .replace(/^- (.+)$/gm, '<li>$1</li>')
          .replace(/^(\d+)\. (.+)$/gm, '<li>$2</li>')
          .replace(/(<li>.*<\/li>\n?)+/g, '<ul>$&</ul>')
          .replace(/\n\n/g, '</p><p>')
        }
      </body>
      </html>
    `;

    const blob = new Blob([htmlContent], { type: "text/html" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/[^a-z0-9]/gi, "_")}_minutes.html`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
    
    setIsGeneratingPdf(false);
    toast({ 
      title: "Downloaded", 
      description: "HTML document downloaded. Open it in a browser and use Print → Save as PDF for a proper PDF." 
    });
  };

  const handleSendEmail = () => {
    const subject = encodeURIComponent(`Meeting Notes: ${title}`);
    const body = encodeURIComponent(emailBody);
    const recipients = participants
      ?.filter(p => p.email)
      .map(p => p.email)
      .join(",") || "";
    
    window.location.href = `mailto:${recipients}?subject=${subject}&body=${body}`;
  };

  const totalItems = items.length;

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center gap-2">
              <Share2 className="h-5 w-5" />
              Export & Share
            </CardTitle>
            <CardDescription>
              {totalItems} items detected. Export or share meeting notes.
            </CardDescription>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <div className="flex flex-wrap gap-2">
          {/* Copy dropdown */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" className="gap-2">
                {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                {copied ? "Copied!" : "Copy"}
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent>
              <DropdownMenuItem onClick={handleCopyMarkdown}>
                <FileText className="mr-2 h-4 w-4" />
                Copy as Markdown
              </DropdownMenuItem>
              <DropdownMenuItem onClick={handleCopyPlainText}>
                <FileText className="mr-2 h-4 w-4" />
                Copy as Plain Text
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>

          {/* Download dropdown */}
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button variant="outline" className="gap-2">
                {isGeneratingPdf ? (
                  <Loader2 className="h-4 w-4 animate-spin" />
                ) : (
                  <Download className="h-4 w-4" />
                )}
                Download
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent>
              <DropdownMenuItem onClick={handleDownloadMarkdown}>
                <FileText className="mr-2 h-4 w-4" />
                Download Markdown (.md)
              </DropdownMenuItem>
              <DropdownMenuItem onClick={handleDownloadPdf}>
                <FileText className="mr-2 h-4 w-4" />
                Download HTML/PDF
              </DropdownMenuItem>
            </DropdownMenuContent>
          </DropdownMenu>

          {/* Email button */}
          <Button onClick={handleSendEmail} className="gap-2">
            <Mail className="h-4 w-4" />
            Email Notes
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}
