import * as React from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Download, Copy, Check, FileText, Clock, CheckSquare, Gavel, HelpCircle } from "lucide-react";
import { formatDuration } from "@/lib/conversations";
import { getItemTypeLabel, type MeetingItemType } from "@/lib/phraseDetection";
import type { MeetingItem } from "@/hooks/useMeetingItems";

interface MeetingMinutesProps {
  title: string;
  date: Date;
  durationMs: number;
  items: MeetingItem[];
  grouped: Record<MeetingItemType, MeetingItem[]>;
  summary?: {
    key_points?: string[];
    decisions?: string[];
    action_items?: string[];
    open_questions?: string[];
  } | null;
  transcript?: Array<{ text: string; start_ms: number }>;
}

function generateMarkdown({
  title,
  date,
  durationMs,
  items,
  grouped,
  summary,
}: MeetingMinutesProps): string {
  const lines: string[] = [];
  
  lines.push(`# Meeting Minutes: ${title}`);
  lines.push("");
  lines.push(`**Date:** ${date.toLocaleDateString()} at ${date.toLocaleTimeString()}`);
  lines.push(`**Duration:** ${formatDuration(durationMs)}`);
  lines.push("");

  // AI Summary section
  if (summary) {
    lines.push("## Summary");
    lines.push("");
    
    if (summary.key_points?.length) {
      lines.push("### Key Points");
      summary.key_points.forEach((kp) => lines.push(`- ${kp}`));
      lines.push("");
    }
  }

  // Detected items by category
  const sections: Array<{ type: MeetingItemType; icon: string; title: string }> = [
    { type: "action_item", icon: "✅", title: "Action Items" },
    { type: "decision", icon: "⚖️", title: "Decisions Made" },
    { type: "question", icon: "❓", title: "Open Questions" },
    { type: "deferred", icon: "⏰", title: "Deferred Items" },
  ];

  for (const section of sections) {
    const sectionItems = grouped[section.type];
    if (sectionItems.length === 0) continue;

    lines.push(`## ${section.icon} ${section.title}`);
    lines.push("");
    
    sectionItems.forEach((item, i) => {
      const owner = item.owner ? ` *(Owner: ${item.owner})*` : "";
      const timestamp = `[${formatDuration(item.timestampMs)}]`;
      lines.push(`${i + 1}. ${item.content}${owner} ${timestamp}`);
    });
    lines.push("");
  }

  // AI-extracted items (from summary) if different
  if (summary?.action_items?.length && grouped.action_item.length === 0) {
    lines.push("## ✅ Action Items (AI Extracted)");
    lines.push("");
    summary.action_items.forEach((ai, i) => lines.push(`${i + 1}. ${ai}`));
    lines.push("");
  }

  if (summary?.decisions?.length && grouped.decision.length === 0) {
    lines.push("## ⚖️ Decisions (AI Extracted)");
    lines.push("");
    summary.decisions.forEach((d, i) => lines.push(`${i + 1}. ${d}`));
    lines.push("");
  }

  if (summary?.open_questions?.length && grouped.question.length === 0) {
    lines.push("## ❓ Open Questions (AI Extracted)");
    lines.push("");
    summary.open_questions.forEach((q, i) => lines.push(`${i + 1}. ${q}`));
    lines.push("");
  }

  lines.push("---");
  lines.push(`*Generated by ConvoIQ on ${new Date().toLocaleString()}*`);

  return lines.join("\n");
}

export function MeetingMinutes(props: MeetingMinutesProps) {
  const { title, date, durationMs, items, grouped, summary } = props;
  const [copied, setCopied] = React.useState(false);
  const [format, setFormat] = React.useState<"preview" | "markdown">("preview");

  const markdown = React.useMemo(() => generateMarkdown(props), [props]);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(markdown);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([markdown], { type: "text/markdown" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${title.replace(/[^a-z0-9]/gi, "_")}_minutes.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  const totalItems = items.length;

  return (
    <Card>
      <CardHeader>
        <div className="flex items-center justify-between">
          <div>
            <CardTitle className="flex items-center gap-2">
              <FileText className="h-5 w-5" />
              Meeting Minutes
            </CardTitle>
            <CardDescription>
              Download or copy formatted meeting minutes with all detected items.
            </CardDescription>
          </div>
          <div className="flex gap-2">
            <Button variant="outline" size="sm" onClick={handleCopy}>
              {copied ? <Check className="mr-1.5 h-4 w-4" /> : <Copy className="mr-1.5 h-4 w-4" />}
              {copied ? "Copied!" : "Copy"}
            </Button>
            <Button size="sm" onClick={handleDownload}>
              <Download className="mr-1.5 h-4 w-4" />
              Download .md
            </Button>
          </div>
        </div>
      </CardHeader>
      <CardContent>
        <Tabs value={format} onValueChange={(v) => setFormat(v as "preview" | "markdown")}>
          <TabsList className="mb-3">
            <TabsTrigger value="preview">Preview</TabsTrigger>
            <TabsTrigger value="markdown">Markdown</TabsTrigger>
          </TabsList>

          <TabsContent value="preview" className="space-y-4">
            {/* Header */}
            <div className="border-b pb-3">
              <h2 className="text-lg font-semibold">{title}</h2>
              <div className="text-sm text-muted-foreground">
                {date.toLocaleDateString()} at {date.toLocaleTimeString()} • {formatDuration(durationMs)}
              </div>
            </div>

            {/* Summary */}
            {summary?.key_points?.length ? (
              <div>
                <h3 className="mb-2 font-medium">Key Points</h3>
                <ul className="list-inside list-disc space-y-1 text-sm text-muted-foreground">
                  {summary.key_points.map((kp, i) => (
                    <li key={i}>{kp}</li>
                  ))}
                </ul>
              </div>
            ) : null}

            {/* Detected Items */}
            {totalItems === 0 ? (
              <div className="py-4 text-center text-sm text-muted-foreground">
                No meeting items detected. Items will appear here when phrase detection finds action items, decisions, questions, or deferred topics.
              </div>
            ) : (
              <div className="grid gap-4 md:grid-cols-2">
                {grouped.action_item.length > 0 && (
                  <div>
                    <h3 className="mb-2 flex items-center gap-1.5 font-medium">
                      <CheckSquare className="h-4 w-4 text-blue-500" />
                      Action Items ({grouped.action_item.length})
                    </h3>
                    <ul className="space-y-1 text-sm">
                      {grouped.action_item.map((item, i) => (
                        <li key={item.id} className="flex gap-2">
                          <span className="text-muted-foreground">{i + 1}.</span>
                          <span>{item.content}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {grouped.decision.length > 0 && (
                  <div>
                    <h3 className="mb-2 flex items-center gap-1.5 font-medium">
                      <Gavel className="h-4 w-4 text-green-500" />
                      Decisions ({grouped.decision.length})
                    </h3>
                    <ul className="space-y-1 text-sm">
                      {grouped.decision.map((item, i) => (
                        <li key={item.id} className="flex gap-2">
                          <span className="text-muted-foreground">{i + 1}.</span>
                          <span>{item.content}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {grouped.question.length > 0 && (
                  <div>
                    <h3 className="mb-2 flex items-center gap-1.5 font-medium">
                      <HelpCircle className="h-4 w-4 text-purple-500" />
                      Open Questions ({grouped.question.length})
                    </h3>
                    <ul className="space-y-1 text-sm">
                      {grouped.question.map((item, i) => (
                        <li key={item.id} className="flex gap-2">
                          <span className="text-muted-foreground">{i + 1}.</span>
                          <span>{item.content}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}

                {grouped.deferred.length > 0 && (
                  <div>
                    <h3 className="mb-2 flex items-center gap-1.5 font-medium">
                      <Clock className="h-4 w-4 text-yellow-500" />
                      Deferred ({grouped.deferred.length})
                    </h3>
                    <ul className="space-y-1 text-sm">
                      {grouped.deferred.map((item, i) => (
                        <li key={item.id} className="flex gap-2">
                          <span className="text-muted-foreground">{i + 1}.</span>
                          <span>{item.content}</span>
                        </li>
                      ))}
                    </ul>
                  </div>
                )}
              </div>
            )}
          </TabsContent>

          <TabsContent value="markdown">
            <pre className="max-h-80 overflow-auto rounded-md bg-muted p-3 text-xs">
              {markdown}
            </pre>
          </TabsContent>
        </Tabs>
      </CardContent>
    </Card>
  );
}
